# Generated by Django 4.2.2 on 2023-06-27 02:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id_kelas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=255)),
                ('jurusan', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_hp', models.BigIntegerField()),
                ('password', models.CharField(max_length=255)),
                ('is_login', models.BooleanField(default=False)),
                ('create_dtm', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('id_kelas', models.ForeignKey(db_column='id_kelas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelas')),
                ('id_parent_user', models.ForeignKey(db_column='id_parent_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_users', to='app.userdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kelas',
            name='id_user',
            field=models.ForeignKey(db_column='id_guru', on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
    ]
