# Generated by Django 4.2.2 on 2023-06-27 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPiket',
            fields=[
                ('id_piket', models.AutoField(primary_key=True, serialize=False)),
                ('hari', models.CharField(max_length=10, null=True)),
                ('id_kelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelas')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
