# Generated by Django 4.2.2 on 2023-06-27 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jadwalpiket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalpiket',
            name='id_kelas',
            field=models.ForeignKey(db_column='id_kelas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelas'),
        ),
        migrations.AlterField(
            model_name='jadwalpiket',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
