# Generated by Django 4.2.2 on 2023-07-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jadwalpiket_id_kelas_alter_jadwalpiket_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kas',
            fields=[
                ('id_trx_kas', models.AutoField(primary_key=True, serialize=False)),
                ('nominal', models.BigIntegerField(db_column='nominal', null=True)),
                ('w1', models.BooleanField(default=False)),
                ('w1_dtm', models.DateTimeField()),
                ('w2', models.BooleanField(default=False)),
                ('w2_dtm', models.DateTimeField()),
                ('w3', models.BooleanField(default=False)),
                ('w3_dtm', models.DateTimeField()),
                ('w4', models.BooleanField(default=False)),
                ('w4_dtm', models.DateTimeField()),
                ('w5', models.BooleanField(default=False)),
                ('w5_dtm', models.DateTimeField()),
                ('id_kelas', models.ForeignKey(db_column='id_kelas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelas')),
                ('id_user', models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
