# Generated by Django 4.2.2 on 2023-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_kas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kas',
            name='yearmonth',
            field=models.BigIntegerField(null=True),
        ),
    ]
