# Generated by Django 4.2.2 on 2023-07-03 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_kas_yearmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelajaran',
            fields=[
                ('id_pelajaran', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelajaran', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_guru', models.ForeignKey(db_column='id_guru', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('id_jadwalpelajaran', models.AutoField(primary_key=True, serialize=False)),
                ('hari', models.CharField(max_length=10, null=True)),
                ('jam_pelajaran', models.CharField(max_length=10, null=True)),
                ('id_kelas', models.ForeignKey(db_column='id_kelas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelas')),
                ('id_pelajaran', models.ForeignKey(db_column='id_pelajaran', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pelajaran')),
            ],
        ),
    ]
