# Generated by Django 4.2.2 on 2023-07-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userdata_nis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='nis',
            field=models.BigIntegerField(null=True),
        ),
    ]
