# Generated by Django 4.2.2 on 2023-07-09 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_notifikasi_notifikasi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi_user',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
