# Generated by Django 4.2.2 on 2023-07-10 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_notifikasi_user_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriTransaksiKas',
            fields=[
                ('id_historiKas', models.AutoField(primary_key=True, serialize=False)),
                ('deskripsi', models.TextField(null=True)),
                ('jenis', models.SmallIntegerField(default=1)),
                ('tanggal_histori', models.DateTimeField(auto_now_add=True)),
                ('id_kelas', models.ForeignKey(db_column='id_kelas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelas')),
                ('id_user', models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
