# Generated by Django 4.2.2 on 2023-07-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_historitransaksikas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historitransaksikas',
            name='nominal',
            field=models.BigIntegerField(db_column='nominal', null=True),
        ),
        migrations.AlterField(
            model_name='tugasuser',
            name='status_tugas',
            field=models.SmallIntegerField(default=0),
        ),
    ]
