# Generated by Django 4.2.2 on 2023-07-10 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_historitransaksikas_nominal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingKelas',
            fields=[
                ('id_boarding', models.AutoField(primary_key=True, serialize=False)),
                ('pesan', models.TextField(null=True)),
                ('path_file', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_kelas', models.ForeignKey(db_column='id_kelas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kelas')),
                ('pengirim', models.ForeignKey(db_column='pengirim', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
